<?php

/**
 * BaseFeesStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $batch_start_year
 * @property integer $amount
 * @property integer $fees_type
 * @property FeesTypes $Type
 * 
 * @method integer       getBatchStartYear()   Returns the current record's "batch_start_year" value
 * @method integer       getAmount()           Returns the current record's "amount" value
 * @method integer       getFeesType()         Returns the current record's "fees_type" value
 * @method FeesTypes     getType()             Returns the current record's "Type" value
 * @method FeesStructure setBatchStartYear()   Sets the current record's "batch_start_year" value
 * @method FeesStructure setAmount()           Sets the current record's "amount" value
 * @method FeesStructure setFeesType()         Sets the current record's "fees_type" value
 * @method FeesStructure setType()             Sets the current record's "Type" value
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeesStructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fees_structure');
        $this->hasColumn('batch_start_year', 'integer', 64, array(
             'type' => 'integer',
             'length' => 64,
             ));
        $this->hasColumn('amount', 'integer', 64, array(
             'type' => 'integer',
             'length' => 64,
             ));
        $this->hasColumn('fees_type', 'integer', 64, array(
             'type' => 'integer',
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FeesTypes as Type', array(
             'local' => 'fees_type',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}