<?php

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $course_type
 * @property integer $total_sections
 * @property CourseTypes $CourseCategory
 * @property Doctrine_Collection $Student
 * @property Doctrine_Collection $OtherUser
 * @property Doctrine_Collection $Subjects
 * @property Doctrine_Collection $StudentClassroom
 * @property Doctrine_Collection $Period
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getCourseType()       Returns the current record's "course_type" value
 * @method integer             getTotalSections()    Returns the current record's "total_sections" value
 * @method CourseTypes         getCourseCategory()   Returns the current record's "CourseCategory" value
 * @method Doctrine_Collection getStudent()          Returns the current record's "Student" collection
 * @method Doctrine_Collection getOtherUser()        Returns the current record's "OtherUser" collection
 * @method Doctrine_Collection getSubjects()         Returns the current record's "Subjects" collection
 * @method Doctrine_Collection getStudentClassroom() Returns the current record's "StudentClassroom" collection
 * @method Doctrine_Collection getPeriod()           Returns the current record's "Period" collection
 * @method Department          setName()             Sets the current record's "name" value
 * @method Department          setCourseType()       Sets the current record's "course_type" value
 * @method Department          setTotalSections()    Sets the current record's "total_sections" value
 * @method Department          setCourseCategory()   Sets the current record's "CourseCategory" value
 * @method Department          setStudent()          Sets the current record's "Student" collection
 * @method Department          setOtherUser()        Sets the current record's "OtherUser" collection
 * @method Department          setSubjects()         Sets the current record's "Subjects" collection
 * @method Department          setStudentClassroom() Sets the current record's "StudentClassroom" collection
 * @method Department          setPeriod()           Sets the current record's "Period" collection
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('course_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('total_sections', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CourseTypes as CourseCategory', array(
             'local' => 'course_type',
             'foreign' => 'id'));

        $this->hasMany('Student', array(
             'local' => 'id',
             'foreign' => 'department'));

        $this->hasMany('OtherUser', array(
             'local' => 'id',
             'foreign' => 'dept_id'));

        $this->hasMany('Subjects', array(
             'local' => 'id',
             'foreign' => 'dept_id'));

        $this->hasMany('StudentClassroom', array(
             'local' => 'id',
             'foreign' => 'dept_id'));

        $this->hasMany('Period', array(
             'local' => 'id',
             'foreign' => 'dept_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}