<?php

/**
 * BaseSubjects
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $batch_year
 * @property integer $semester
 * @property integer $dept_id
 * @property string $name
 * @property string $code
 * @property Department $Department
 * @property Doctrine_Collection $TimetableAssignment
 * 
 * @method integer             getBatchYear()           Returns the current record's "batch_year" value
 * @method integer             getSemester()            Returns the current record's "semester" value
 * @method integer             getDeptId()              Returns the current record's "dept_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getCode()                Returns the current record's "code" value
 * @method Department          getDepartment()          Returns the current record's "Department" value
 * @method Doctrine_Collection getTimetableAssignment() Returns the current record's "TimetableAssignment" collection
 * @method Subjects            setBatchYear()           Sets the current record's "batch_year" value
 * @method Subjects            setSemester()            Sets the current record's "semester" value
 * @method Subjects            setDeptId()              Sets the current record's "dept_id" value
 * @method Subjects            setName()                Sets the current record's "name" value
 * @method Subjects            setCode()                Sets the current record's "code" value
 * @method Subjects            setDepartment()          Sets the current record's "Department" value
 * @method Subjects            setTimetableAssignment() Sets the current record's "TimetableAssignment" collection
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubjects extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subjects');
        $this->hasColumn('batch_year', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dept_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('code', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Department', array(
             'local' => 'dept_id',
             'foreign' => 'id'));

        $this->hasMany('TimetableAssignment', array(
             'local' => 'id',
             'foreign' => 'subject_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}