<?php

/**
 * BaseManageUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $to_group
 * @property string $to_dept
 * @property string $user_name
 * @property string $email_id
 * 
 * @method string     getToGroup()   Returns the current record's "to_group" value
 * @method string     getToDept()    Returns the current record's "to_dept" value
 * @method string     getUserName()  Returns the current record's "user_name" value
 * @method string     getEmailId()   Returns the current record's "email_id" value
 * @method ManageUser setToGroup()   Sets the current record's "to_group" value
 * @method ManageUser setToDept()    Sets the current record's "to_dept" value
 * @method ManageUser setUserName()  Sets the current record's "user_name" value
 * @method ManageUser setEmailId()   Sets the current record's "email_id" value
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManageUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manage_user');
        $this->hasColumn('to_group', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('to_dept', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('user_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('email_id', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}