<?php

/**
 * BaseFeesTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $is_varying
 * @property Doctrine_Collection $FeesStructure
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method boolean             getIsVarying()     Returns the current record's "is_varying" value
 * @method Doctrine_Collection getFeesStructure() Returns the current record's "FeesStructure" collection
 * @method FeesTypes           setName()          Sets the current record's "name" value
 * @method FeesTypes           setIsVarying()     Sets the current record's "is_varying" value
 * @method FeesTypes           setFeesStructure() Sets the current record's "FeesStructure" collection
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeesTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fees_types');
        $this->hasColumn('name', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('is_varying', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FeesStructure', array(
             'local' => 'id',
             'foreign' => 'fees_type'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}