<?php

/**
 * BaseStudentClassroom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $dept_id
 * @property integer $section_no
 * @property Student $Stud
 * @property Department $Department
 * 
 * @method integer          getStudentId()  Returns the current record's "student_id" value
 * @method integer          getDeptId()     Returns the current record's "dept_id" value
 * @method integer          getSectionNo()  Returns the current record's "section_no" value
 * @method Student          getStud()       Returns the current record's "Stud" value
 * @method Department       getDepartment() Returns the current record's "Department" value
 * @method StudentClassroom setStudentId()  Sets the current record's "student_id" value
 * @method StudentClassroom setDeptId()     Sets the current record's "dept_id" value
 * @method StudentClassroom setSectionNo()  Sets the current record's "section_no" value
 * @method StudentClassroom setStud()       Sets the current record's "Stud" value
 * @method StudentClassroom setDepartment() Sets the current record's "Department" value
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentClassroom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_classroom');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dept_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('section_no', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student as Stud', array(
             'local' => 'student_id',
             'foreign' => 'student_id'));

        $this->hasOne('Department', array(
             'local' => 'dept_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}