<?php

/**
 * BaseCourseTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $total_years
 * @property Doctrine_Collection $Student
 * @property Doctrine_Collection $Department
 * @property Doctrine_Collection $FeesStructure
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getTotalYears()    Returns the current record's "total_years" value
 * @method Doctrine_Collection getStudent()       Returns the current record's "Student" collection
 * @method Doctrine_Collection getDepartment()    Returns the current record's "Department" collection
 * @method Doctrine_Collection getFeesStructure() Returns the current record's "FeesStructure" collection
 * @method CourseTypes         setName()          Sets the current record's "name" value
 * @method CourseTypes         setTotalYears()    Sets the current record's "total_years" value
 * @method CourseTypes         setStudent()       Sets the current record's "Student" collection
 * @method CourseTypes         setDepartment()    Sets the current record's "Department" collection
 * @method CourseTypes         setFeesStructure() Sets the current record's "FeesStructure" collection
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourseTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_types');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('total_years', 'integer', 64, array(
             'type' => 'integer',
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Student', array(
             'local' => 'id',
             'foreign' => 'course_type'));

        $this->hasMany('Department', array(
             'local' => 'id',
             'foreign' => 'course_type'));

        $this->hasMany('FeesStructure', array(
             'local' => 'id',
             'foreign' => 'course_type'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}