<?php

/**
 * BaseStudentVaryingFees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $acad_year_no
 * @property integer $fees_type
 * @property integer $route_id
 * @property Student $Stud
 * 
 * @method integer            getStudentId()    Returns the current record's "student_id" value
 * @method integer            getAcadYearNo()   Returns the current record's "acad_year_no" value
 * @method integer            getFeesType()     Returns the current record's "fees_type" value
 * @method integer            getRouteId()      Returns the current record's "route_id" value
 * @method Student            getStud()         Returns the current record's "Stud" value
 * @method StudentVaryingFees setStudentId()    Sets the current record's "student_id" value
 * @method StudentVaryingFees setAcadYearNo()   Sets the current record's "acad_year_no" value
 * @method StudentVaryingFees setFeesType()     Sets the current record's "fees_type" value
 * @method StudentVaryingFees setRouteId()      Sets the current record's "route_id" value
 * @method StudentVaryingFees setStud()         Sets the current record's "Stud" value
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentVaryingFees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_varying_fees');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('acad_year_no', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fees_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('route_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student as Stud', array(
             'local' => 'student_id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}