<?php

/**
 * BaseSchoolDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property string $institution_name
 * @property float $total_percent_marks
 * 
 * @method integer       getStudentId()           Returns the current record's "student_id" value
 * @method string        getInstitutionName()     Returns the current record's "institution_name" value
 * @method float         getTotalPercentMarks()   Returns the current record's "total_percent_marks" value
 * @method SchoolDetails setStudentId()           Sets the current record's "student_id" value
 * @method SchoolDetails setInstitutionName()     Sets the current record's "institution_name" value
 * @method SchoolDetails setTotalPercentMarks()   Sets the current record's "total_percent_marks" value
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchoolDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school_details');
        $this->hasColumn('student_id', 'integer', 64, array(
             'type' => 'integer',
             'length' => 64,
             ));
        $this->hasColumn('institution_name', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('total_percent_marks', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}