<?php

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $course_type
 * @property CourseTypes $CourseCategory
 * @property Doctrine_Collection $Student
 * @property Doctrine_Collection $OtherUser
 * @property Doctrine_Collection $Subjects
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method integer             getCourseType()     Returns the current record's "course_type" value
 * @method CourseTypes         getCourseCategory() Returns the current record's "CourseCategory" value
 * @method Doctrine_Collection getStudent()        Returns the current record's "Student" collection
 * @method Doctrine_Collection getOtherUser()      Returns the current record's "OtherUser" collection
 * @method Doctrine_Collection getSubjects()       Returns the current record's "Subjects" collection
 * @method Department          setName()           Sets the current record's "name" value
 * @method Department          setCourseType()     Sets the current record's "course_type" value
 * @method Department          setCourseCategory() Sets the current record's "CourseCategory" value
 * @method Department          setStudent()        Sets the current record's "Student" collection
 * @method Department          setOtherUser()      Sets the current record's "OtherUser" collection
 * @method Department          setSubjects()       Sets the current record's "Subjects" collection
 * 
 * @package    KVCET
 * @subpackage model
 * @author     Natu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('course_type', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CourseTypes as CourseCategory', array(
             'local' => 'course_type',
             'foreign' => 'id'));

        $this->hasMany('Student', array(
             'local' => 'id',
             'foreign' => 'department'));

        $this->hasMany('OtherUser', array(
             'local' => 'id',
             'foreign' => 'department'));

        $this->hasMany('Subjects', array(
             'local' => 'id',
             'foreign' => 'dept_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}