<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addstudent extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('student', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => 8,
        'autoincrement' => true,
        'primary' => true,
      ),
      'student_id' =>
      array(
        'type' => 'integer',
        'length' => 64,
      ),
      'first_name' =>
      array(
        'type' => 'string',
        'length' => 64,
      ),
      'last_name' =>
      array(
        'type' => 'string',
        'length' => 64,
      ),
      'admission_no' =>
      array(
        'type' => 'integer',
        'length' => 8,
      ),
      'admission_date' =>
      array(
        'type' => 'date',
        'length' => 25,
      ),
      'admission_mode' =>
      array(
        'type' => 'tinyint',
        'length' => 1,
      ),
      'department' =>
      array(
        'type' => 'integer',
        'length' => 8,
      ),
      'dob' =>
      array(
        'type' => 'date',
        'length' => 25,
      ),
      'gender' =>
      array(
        'type' => 'boolean',
        'length' => 25,
      ),
      'address' =>
      array(
        'type' => 'string',
        'length' => 1000,
      ),
      'city' =>
      array(
        'type' => 'string',
        'length' => 200,
      ),
      'state' =>
      array(
        'type' => 'string',
        'length' => 200,
      ),
      'pincode' =>
      array(
        'type' => 'integer',
        'length' => 10,
      ),
      'mobile' =>
      array(
        'type' => 'integer',
        'length' => 15,
      ),
      'email' =>
      array(
        'type' => 'string',
        'length' => 100,
      ),
      'photo_id' =>
      array(
        'type' => 'integer',
        'length' => 64,
      ),
      'parent_first_name' =>
      array(
        'type' => 'string',
        'length' => 64,
      ),
      'parent_last_name' =>
      array(
        'type' => 'string',
        'length' => 64,
      ),
      'parent_gender' =>
      array(
        'type' => 'boolean',
        'length' => 25,
      ),
      'parent_occupation' =>
      array(
        'type' => 'string',
        'length' => 100,
      ),
      'parent_email' =>
      array(
        'type' => 'string',
        'length' => 100,
      ),
      'parent_phone' =>
      array(
        'type' => 'integer',
        'length' => 20,
      ),
      'parent_mobile' =>
      array(
        'type' => 'integer',
        'length' => 20,
      ),
      'institution_name' =>
      array(
        'type' => 'string',
        'length' => '200',
      ),
      'total_percent_marks' =>
      array(
        'type' => 'float',
        'length' => '',
      ),
      'created_at' =>
      array(
        'notnull' => true,
        'type' => 'timestamp',
        'length' => 25,
      ),
      'updated_at' =>
      array(
        'notnull' => true,
        'type' => 'timestamp',
        'length' => 25,
      ),
      'deleted_at' =>
      array(
        'notnull' => false,
        'type' => 'timestamp',
        'length' => 25,
      ),
    ), array(
      'indexes' =>
      array(),
      'primary' =>
      array(
        0 => 'id',
      ),
      'collate' => 'utf8_unicode_ci',
      'charset' => 'UTF8',
    ));
  }

  public function down()
  {
    $this->dropTable('student');
  }
}