<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('course_types', 'total_years', 'integer', '64', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('course_types', 'total_years');
    }
}