<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('department', 'department_course_type_course_types_id', array(
             'name' => 'department_course_type_course_types_id',
             'local' => 'course_type',
             'foreign' => 'id',
             'foreignTable' => 'course_types',
             ));
        $this->createForeignKey('student', 'student_course_type_course_types_id', array(
             'name' => 'student_course_type_course_types_id',
             'local' => 'course_type',
             'foreign' => 'id',
             'foreignTable' => 'course_types',
             ));
        $this->addIndex('department', 'department_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
        $this->addIndex('student', 'student_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('department', 'department_course_type_course_types_id');
        $this->dropForeignKey('student', 'student_course_type_course_types_id');
        $this->removeIndex('department', 'department_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
        $this->removeIndex('student', 'student_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
    }
}