<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('department', 'course_type', 'integer', '8', array(
             ));
        $this->addColumn('student', 'course_type', 'integer', '8', array(
             ));
        $this->addColumn('student', 'batch_year', 'integer', '8', array(
             ));
        $this->addColumn('student', 'is_lateral', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('department', 'course_type');
        $this->removeColumn('student', 'course_type');
        $this->removeColumn('student', 'batch_year');
        $this->removeColumn('student', 'is_lateral');
    }
}