<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('fees_structure', 'fees_structure_fees_type_fees_types_id', array(
             'name' => 'fees_structure_fees_type_fees_types_id',
             'local' => 'fees_type',
             'foreign' => 'id',
             'foreignTable' => 'fees_types',
             ));
        $this->addIndex('fees_structure', 'fees_structure_fees_type', array(
             'fields' => 
             array(
              0 => 'fees_type',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('fees_structure', 'fees_structure_fees_type_fees_types_id');
        $this->removeIndex('fees_structure', 'fees_structure_fees_type', array(
             'fields' => 
             array(
              0 => 'fees_type',
             ),
             ));
    }
}