<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('fees_structure', 'fees_structure_course_type_course_types_id', array(
             'name' => 'fees_structure_course_type_course_types_id',
             'local' => 'course_type',
             'foreign' => 'id',
             'foreignTable' => 'course_types',
             ));
        $this->addIndex('fees_structure', 'fees_structure_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('fees_structure', 'fees_structure_course_type_course_types_id');
        $this->removeIndex('fees_structure', 'fees_structure_course_type', array(
             'fields' => 
             array(
              0 => 'course_type',
             ),
             ));
    }
}