<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('fees_discount', 'fees_discount_student_id_student_student_id', array(
             'name' => 'fees_discount_student_id_student_student_id',
             'local' => 'student_id',
             'foreign' => 'student_id',
             'foreignTable' => 'student',
             ));
        $this->addIndex('fees_discount', 'fees_discount_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->addIndex('student', 'student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('fees_discount', 'fees_discount_student_id_student_student_id');
        $this->removeIndex('fees_discount', 'fees_discount_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->removeIndex('student', 'student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }
}