<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->createForeignKey('subjects', 'subjects_dept_id_department_id', array(
        'name' => 'subjects_dept_id_department_id',
        'local' => 'dept_id',
        'foreign' => 'id',
        'foreignTable' => 'department',
      ));
      $this->addIndex('subjects', 'subjects_dept_id', array(
        'fields' =>
        array(
          0 => 'dept_id',
        ),
      ));
    }

    public function down()
    {
      $this->dropForeignKey('subjects', 'subjects_dept_id_department_id');
      $this->removeIndex('subjects', 'subjects_dept_id', array(
        'fields' =>
        array(
          0 => 'dept_id',
        ),
      ));
    }
}