<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('other_user', 'middle_name');
        $this->removeColumn('other_user', 'user_name');
        $this->removeColumn('other_user', 'group_id');
        $this->addColumn('other_user', 'last_name', 'string', '64', array(
             ));
        $this->addColumn('other_user', 'department', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('other_user', 'middle_name', 'string', '64', array(
             ));
        $this->addColumn('other_user', 'user_name', 'string', '64', array(
             ));
        $this->addColumn('other_user', 'group_id', 'integer', '8', array(
             ));
        $this->removeColumn('other_user', 'last_name');
        $this->removeColumn('other_user', 'department');
    }
}