<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('other_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'middle_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'email_address' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             ));
    }

    public function down()
    {
        $this->dropTable('other_user');
    }
}