<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('other_user', 'other_user_group_id_sf_guard_group_id', array(
             'name' => 'other_user_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             ));
        $this->addIndex('other_user', 'other_user_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('other_user', 'other_user_group_id_sf_guard_group_id');
        $this->removeIndex('other_user', 'other_user_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }
}