<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('period', 'period_dept_id_department_id', array(
             'name' => 'period_dept_id_department_id',
             'local' => 'dept_id',
             'foreign' => 'id',
             'foreignTable' => 'department',
             ));
        $this->addIndex('period', 'period_dept_id', array(
             'fields' => 
             array(
              0 => 'dept_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('period', 'period_dept_id_department_id');
        $this->removeIndex('period', 'period_dept_id', array(
             'fields' => 
             array(
              0 => 'dept_id',
             ),
             ));
    }
}