<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('timetable_assignment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'subject_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'staff_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'period_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'day_no' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             ));
    }

    public function down()
    {
        $this->dropTable('timetable_assignment');
    }
}