<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_assignment', 'timetable_assignment_staff_id_other_user_user_id', array(
             'name' => 'timetable_assignment_staff_id_other_user_user_id',
             'local' => 'staff_id',
             'foreign' => 'user_id',
             'foreignTable' => 'other_user',
             ));
        $this->createForeignKey('timetable_assignment', 'timetable_assignment_period_id_period_id', array(
             'name' => 'timetable_assignment_period_id_period_id',
             'local' => 'period_id',
             'foreign' => 'id',
             'foreignTable' => 'period',
             ));
        $this->addIndex('timetable_assignment', 'timetable_assignment_staff_id', array(
             'fields' => 
             array(
              0 => 'staff_id',
             ),
             ));
        $this->addIndex('timetable_assignment', 'timetable_assignment_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_assignment', 'timetable_assignment_staff_id_other_user_user_id');
        $this->dropForeignKey('timetable_assignment', 'timetable_assignment_period_id_period_id');
        $this->removeIndex('timetable_assignment', 'timetable_assignment_staff_id', array(
             'fields' => 
             array(
              0 => 'staff_id',
             ),
             ));
        $this->removeIndex('timetable_assignment', 'timetable_assignment_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }
}