<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('manage_user');
        $this->addColumn('other_user', 'group_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->createTable('manage_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'to_group' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'to_dept' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'email_id' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => '',
             ));
        $this->removeColumn('other_user', 'group_id');
    }
}