all:
  is_secure: true
  credentials: [[DOP, Director]]

setFeesStructure:
  is_secure: true
  credentials: Director

feesCategories:
  is_secure: true
  credentials: Director

addFeesCategory:
  is_secure: true
  credentials: Director

editFeesCategory:
  is_secure: true
  credentials: Director