all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=KVCET'
      username: root
      password: p@ssw0rd
      attributes: { default_table_collate: utf8_unicode_ci }
