<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable {

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('sfGuardGroup');
    }

    /**
     * @author Uday Shankar Singh <udayshankar1306@gmail.com>
     * 
     * @return Array - All the Group in the table
     */
    public function getGroups() {
        $data = $this->createQuery()->fetchArray();
        return $data;
    }

}