<?php

/**
 * DepartmentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object DepartmentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Department');
  }

  public function getDepartments() {
    $data = array();
    $departments = $this->createQuery()->fetchArray();
    foreach($departments as $department) {
      $data['options'][] = $department['name'];
      $data['values'][] = $department['id'];
    }

    return $data;
  }

}