<?php

/**
 * DepartmentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object DepartmentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Department');
  }

  public function getDepartments() {
    $data = array();
    $departments = $this->createQuery()->fetchArray();
    foreach($departments as $department) {
      $data['options'][] = $department['name'];
      $data['values'][] = $department['id'];
    }

    return $data;
  }


  public function getCourseDepartments($courseType) {
    $departments = Doctrine_Query::create()
      ->select('d.id as dept_id, d.name, c.id')
      ->from('Department d')
      ->leftJoin('d.CourseCategory c')
      ->where('d.course_type = ?', $courseType)
      ->fetchArray();

    $data = array();
    foreach($departments as $dept) {
      $data['options'][] = $dept['name'];
      $data['values'][] = $dept['dept_id'];
    }

    return $data;
  }
}