<?php

/**
 * FeesTypesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeesTypesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object FeesTypesTable
   */

  const TUITION_GOVT = 1;
  const TUITION_MGMT = 2;
  const TUITION_FG = 3;
  const BOOKS = 4;
  const TRAINING = 5;
  const HOSTEL_ATTACHED = 6;
  const HOSTEL_COMMON = 7;
  const LUNCH = 8;
  const TRANSPORT = 9;
  const OTHER = 10;

  public static function getInstance()
  {
    return Doctrine_Core::getTable('FeesTypes');
  }

  public function getAllTypes() {
    $feesTypes = $this->createQuery()->fetchArray();
    $data = array();
    $i = 0;
    foreach($feesTypes as $type) {
      $data[$i]['value'] = $type['id'];
      $data[$i]['name'] = $type['name'];
      $i++;
    }

    return $data;
  }

}