<?php

/**
 * FeesDiscountTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeesDiscountTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object FeesDiscountTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('FeesDiscount');
  }

  public function addDiscount($data) {
    $feesDiscount = new FeesDiscount();
    $feesDiscount->setAcadYearNo($data['acad_year_no']);
    $feesDiscount->setAmount($data['amount']);
    $feesDiscount->setDescription($data['description']);
    $feesDiscount->setStudentId($data['student_id']);
    $feesDiscount->save();
  }

  public function editFeesDiscount($data) {
    $feesDiscount = FeesDiscountTable::getInstance()->find($data['discount_id']);
    $feesDiscount->setAmount($data['amount']);
    $feesDiscount->setDescription($data['description']);
    $feesDiscount->setAcadYearNo($data['acad_year_no']);
    $feesDiscount->save();
  }

  public function getFeesDiscount($student) {
    $paidFees = Doctrine_Query::create()
      ->from('FeesDiscount')
      ->where('student_id = ?', $student->getStudentId())
      ->fetchArray();

    $data = array();
    $i = 0;
    $prevAcadYearNo = 0;
    $formHelper = new formHelper();
    foreach($paidFees as $pf) {
      $acadYearNo = $pf['acad_year_no'];
      if($i == 0) {
        $prevAcadYearNo = $acadYearNo;
      }

      if($prevAcadYearNo != $acadYearNo) {
        $i = 0;
      }

      $data[$acadYearNo][$i]['id'] = $pf['id'];
      $data[$acadYearNo][$i]['description'] = $pf['description'];
      $data[$acadYearNo][$i]['amount'] = $pf['amount'];

      $i++;
    }

    return $data;
  }

}