<?php

/**
 * FeesStructureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeesStructureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeesStructureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeesStructure');
    }
}