<?php

/**
 * FeesTypesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeesTypesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object FeesTypesTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('FeesTypes');
  }

  public function getAllTypes() {
    $feesTypes = $this->createQuery()->fetchArray();
    $data = array();
    $i = 0;
    foreach($feesTypes as $type) {
      $data[$i]['value'] = $type['id'];
      $data[$i]['name'] = $type['name'];
      $i++;
    }

    return $data;
  }

}