<?php

/**
 * ManageUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManageUserTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ManageUserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ManageUser');
    }

    /**
     * @author Uday Shankar Singh <udayshankar1306@gmail.com>
     * 
     * @param Array $groups
     * @return Array - ARRAY OF OPTIONS AND VALUES EXCEPT DIRECTOR AND PRINCIPAL AS THESED ARE ONLY ONE IN EVERY COLLEGE SYSTEM
     */
    public function getRefinedGroups($groups) {

        $result = Array();
        foreach ($groups as $data) {
            if (!in_array($data['id'], array(1, 2))) {
                $result['values'][] = $data['id'];
                $result['options'][] = $data['description'];
            }
        }
        
        return $result;
    }

}