<?php

/**
 * ManageUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManageUserTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ManageUserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ManageUser');
    }

    /**
     * @author Uday Shankar Singh <udayshankar1306@gmail.com>
     * 
     * @param Array $groups
     * @return Array - ARRAY OF OPTIONS AND VALUES EXCEPT DIRECTOR AND PRINCIPAL AS THESED ARE ONLY ONE IN EVERY COLLEGE SYSTEM
     */
    public function getRefinedGroups($groups) {

        $result = Array();
        foreach ($groups as $data) {
            if (!in_array($data['id'], array(1, 2))) {
                $result['values'][] = $data['id'];
                $result['options'][] = $data['description'];
            }
        }

        return $result;
    }

    public function checkUserExsistance($params) {
        $result = $this->createQuery('c')
                ->select('count(*) as count')
                ->from('sfGuardUser c')
                ->where('c.username = ? ', $params['user_mail'])
                ->fetchOne();

        return $result->getCount();
    }

    public function saveUserData($params, $passGenerated) {

        $user = new sfGuardUser();
        $user->setFirstName($params['first_name']);
        $user->setLastName($params['last_name']);
        $user->setEmailAddress($params['user_mail']);
        $user->setUsername($params['user_mail']); // SAVING user_mail AS USER NAME can be changed with user_name IF NEEDED
        $user->setPassword($passGenerated);
        $user->save();

        if ($user->getId()) {
            $userGroup = new sfGuardUserGroup();
            $userGroup->setGroupId($params['user_dept']);
            $userGroup->setUserId($user->getId());
            $userGroup->save();

            return TRUE;
        } else
            return FALSE;
    }

    public function getAllUsers() {
        
    }

}