<?php

/**
 * OtherUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtherUserTable extends Doctrine_Table {
  /**
   * Returns an instance of this class.
   *
   * @return object OtherUserTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('OtherUser');
  }

  public function getStaffs($dept) {
    $staffs = Doctrine_Query::create()
        ->from('OtherUser')
        ->where('dept_id = ?', $dept)
        ->andWhereIn('group_id', array(4, 5))
        ->fetchArray();

    $data = array();
    foreach ($staffs as $staff) {
      $data['options'][] = $staff['first_name'] . " " . $staff['last_name'];
      $data['values'][] = $staff['user_id'];
    }

    return $data;
  }

}