<?php

/**
 * OtherUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtherUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OtherUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OtherUser');
    }
}