<?php

/**
 * SchoolDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchoolDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchoolDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SchoolDetails');
    }
}