<?php

/**
 * StudentClassroomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentClassroomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentClassroomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentClassroom');
    }
}