<?php

/**
 * StudentVaryingFeesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentVaryingFeesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object StudentVaryingFeesTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('StudentVaryingFees');
  }

  public function setStudentFees($student, $data) {

    $academic = new academicHelper();
    $acadYearNo = $academic->getAcadYearNo($student->getBatchYear());

    if($data['accommodation'] == 0) {
      $feesType = ($data['room_type'] == 0) ? 6 : 7;
    } else {
      $feesType = 9;
    }

    $fees = new StudentVaryingFees();
    $fees->setStudentId($student->getStudentId());
    $fees->setAcadYearNo($acadYearNo);
    $fees->setFeesType($feesType);
    $fees->setRouteId($data['route']);
    $fees->save();
  }

}