<?php

/**
 * SubjectsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubjectsTable extends Doctrine_Table {
  /**
   * Returns an instance of this class.
   *
   * @return object SubjectsTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Subjects');
  }

  public function addNewSubject($data) {
    $sub = new Subjects();
    $sub->setName($data['name']);
    $sub->setCode($data['code']);
    $sub->setBatchYear($data['batch']);
    $sub->setDeptId($data['dept']);
    $sub->setSemester($data['sem']);
    $sub->save();
  }

}