<?php

/**
 * TimetableAssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimetableAssignmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TimetableAssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TimetableAssignment');
    }
}