<?php

/**
 * TransportFeesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransportFeesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TransportFeesTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TransportFees');
  }

  public function getRouteTypes() {
    $data = array();
    $routeTypes = $this->createQuery()->fetchArray();
    foreach($routeTypes as $routeType) {
      $data['options'][] = $routeType['route_name'];
      $data['values'][] = $routeType['id'];
    }

    return $data;
  }

}