# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:      /
  param:    { module: sfGuardAuth, action: homePage }

# generic rules
# please, remove them by adding more specific rules

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: login }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

forgot_password:
  url:   /forgot_password
  param: { module: sfGuardAuth, action: forgotPassword }

fees_structure:
  url:  /fees/fees-structure
  param: { module: fees, action: feesStructure }

view_fees_structure:
  url:  /fees/view-fees-structure
  param: { module: fees, action: viewFeesStructure }

set_fees_structure:
  url:  /fees/set-fees-structure
  param: { module: fees, action: setFeesStructure }

get_course_total_years:
  url:  /fees/getCourseTotalYears
  param: { module: fees, action: getCourseTotalYears }

get_course_total_years:
  url:  /getCourseTypeDepartments
  param: { module: admission, action: getCourseTypeDepartments }

fees_categories:
  url:  /fees/fees-categories
  param: { module: fees, action: feesCategories }

add_fees_category:
  url:  /fees/add-fees-category
  param: { module: fees, action: addFeesCategory }

edit_fees_category:
  url:  /fees/edit-fees-category
  param: { module: fees, action: editFeesCategory }

student_fees_dashboard:
  url:  /student/fees/id/:id
  param: { module: fees, action: feesDashboard }

student_add_fees:
  url:  /student/add-fees/id/:id
  param: { module: fees, action: addStudentFees }

search_student:
  url:  /student/search
  param: { module: student, action: searchStudent }

student_profile:
  url:  /profile/studentProfile/id/:id
  param: { module: profile, action: studentProfile }





# Keep these two rules at the bottom of the page to avoid overriding
default_index:
  url:   /:module

default:
  url:   /:module/:action/*
