# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:      /
  param:    { module: sfGuardAuth, action: homePage }

# generic rules
# please, remove them by adding more specific rules

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: login }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

forgot_password:
  url:   /forgot_password
  param: { module: sfGuardAuth, action: forgotPassword }

fees_structure:
  url:  /fees/fees-structure
  param: { module: fees, action: feesStructure }

view_fees_structure:
  url:  /fees/view-fees-structure
  param: { module: fees, action: viewFeesStructure }

set_fees_structure:
  url:  /fees/set-fees-structure
  param: { module: fees, action: setFeesStructure }

get_course_total_years:
  url:  /fees/getCourseTotalYears
  param: { module: fees, action: getCourseTotalYears }

get_course_total_years:
  url:  /getCourseTypeDepartments
  param: { module: admission, action: getCourseTypeDepartments }

fees_categories:
  url:  /fees/fees-categories
  param: { module: fees, action: feesCategories }

add_fees_category:
  url:  /fees/add-fees-category
  param: { module: fees, action: addFeesCategory }

edit_fees_category:
  url:  /fees/edit-fees-category
  param: { module: fees, action: editFeesCategory }

student_fees_dashboard:
  url:  /student/fees/id/:id
  param: { module: fees, action: feesDashboard }

student_add_fees:
  url:  /student/add-fees/id/:id
  param: { module: fees, action: addStudentFees }

student_edit_fees:
  url:  /student/edit-fees/id/:id
  param: { module: fees, action: editStudentFees }

student_add_fees_discount:
  url:  /student/add-fees-discount/id/:id
  param: { module: fees, action: addFeesDiscount }

student_edit_fees_discount:
  url:  /student/edit-fees-discount/id/:id
  param: { module: fees, action: editFeesDiscount }

due_list:
  url:  /fees/due-list
  param: { module: fees, action: dueList }

student_fees_history:
  url:  /student/payment-history/id/:id
  param: { module: fees, action: studentPaymentHistory }

search_student:
  url:  /student/search
  param: { module: student, action: searchStudent }

student_profile:
  url:  /profile/studentProfile/id/:id
  param: { module: profile, action: studentProfile }

exam_subject:
  url:  /exam/subjects
  param: { module: exam, action: viewSubjects }

search_subject:
  url:  /search/subject
  param: { module: exam, action: searchSubject }

add_subject:
  url:  /add/subject
  param: { module: exam, action: addSubject }

edit_subject:
  url:  /exam/edit-subject
  param: { module: exam, action: editSubject }
  
create_user:
  url: /user/new
  param: { module: otherUser, action: new }
  
#edit_user:
#  url: /user/edit
#  param: { module: userManagement, action: edit }
  
delete_user:
  url: /user/delete
  param: { module: otherUser, action: delete }
  
view_user:
  url: /user/list
  param: { module: otherUser, action: list }

timetable_search_classroom:
  url:  /timetable/search-classroom
  param: { module: timetable, action: searchClassroom }

timetable_assign_classroom:
  url:  /student/assign-classroom
  param: { module: timetable, action: assignStudentsClassroom }

timetable_search:
  url:  /timetable/search-timetable
  param: { module: timetable, action: searchTimetable }

show_timetable:
  url:  /timetable/show-timetable
  param: { module: timetable, action: showTimetable }

get_assigned_period:
  url:  /timetable/get-assigned-period
  param: { module: timetable, action: getAssignedPeriod }

assign_period:
  url:  /timetable/assign-period
  param: { module: timetable, action: assignPeriod }

classroom_periods:
  url:  /timetable/get-classroom-periods
  param: { module: timetable, action: getClassroomPeriods }

manage_period:
  url:  /timetable/manage-period
  param: { module: timetable, action: managePeriod }



# Keep these two rules at the bottom of the page to avoid overriding
default_index:
  url:   /:module

default:
  url:   /:module/:action/*
