# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:      /
  param:    { module: sfGuardAuth, action: homePage }

# generic rules
# please, remove them by adding more specific rules

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: login }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

forgot_password:
  url:   /forgot_password
  param: { module: sfGuardAuth, action: forgotPassword }

fees_structure:
  url:  /fees/fees-structure
  param: { module: fees, action: feesStructure }

view_fees_structure:
  url:  /fees/view-fees-structure
  param: { module: fees, action: viewFeesStructure }

set_fees_structure:
  url:  /fees/set-fees-structure
  param: { module: fees, action: setFeesStructure }

get_course_total_years:
  url:  /fees/getCourseTotalYears
  param: { module: fees, action: getCourseTotalYears }

# Keep these two rules at the bottom of the page to avoid overriding
default_index:
  url:   /:module

default:
  url:   /:module/:action/*
