# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        KVCET
    description:  Karpaga Vinayaga College of Engineering and Technology
    keywords:     kvcet
    language:     en

  stylesheets:
    - kvcet.css
    - validationEngine.jquery.css
    - template.css
    - jquery.ui.all.css

  javascripts:
    - lib/jquery-1.5.1.js
    - lib/jquery.validationEngine.js
    - lib/jquery.validationEngine-en.js
    - lib/jquery.ui.core.js
    - lib/jquery.ui.widget.js
    - lib/jquery.ui.datepicker.js
    - lib/jquery.ui.autocomplete.js
    - lib/jquery.ui.position.js
    - lib/lightbox.js
    - lib/underscore-min.js
    - forms/page_helper.js
    - forms/admission_form.js
    - forms/fees_form.js
    - forms/exam_form.js
    - forms/timetable_form.js


  has_layout:     true
  layout:         dashboardLayout