Student:
  actAs:           [Timestampable, SoftDelete]
  columns:
    student_id:         { type: integer(64) }
    first_name:          { type: string(64) }
    last_name:          { type: string(64) }
    admission_no:       { type: integer }
    admission_date:     { type: date }
    admission_mode:     { type: tinyint(1) }
    batch_year:         { type: integer }
    is_lateral:         { type: boolean, default: false }
    course_type:        { type: integer }
    department:         { type: integer }
    dob:                { type: date }
    gender:              { type: boolean }
    address:             { type: string(1000) }
    city:               { type: string(200) }
    state:               { type: string(200) }
    pincode:             { type: integer(10), default: null }
    mobile:              { type: integer(15), default: null }
    email:              { type: string(100) }
    photo_id:            { type: integer(64) }
    parent_first_name:  { type: string(64) }
    parent_last_name:   { type: string(64) }
    parent_gender:      { type: boolean }
    parent_occupation:  { type: string(100) }
    parent_email:       { type: string(100) }
    parent_phone:       { type: integer(20), default: null }
    parent_mobile:      { type: integer(20), default: null }
    institution_name:   { type: string(200) }
    total_percent_marks: { type: float }

  relations:
    User:                { class: sfGuardUser, local: student_id, foreign: id }
    StudDepartment:    { class: Department, local: department, foreign: id }
    StudCourseCategory: { class: CourseTypes, local: course_type, foreign: id }


CourseTypes:
  actAs:           [Timestampable, SoftDelete]
  columns:
    name:          { type: string(64) }
    total_years:  { type: integer(64) }


Department:
  actAs:           [Timestampable, SoftDelete]
  columns:
    name:          { type: string(64) }
    course_type:  { type: integer }

  relations:
    CourseCategory:        { class: CourseTypes, local: course_type, foreign: id }


FeesStructure:
  actAs:           [Timestampable, SoftDelete]
  columns:
    amount:                  { type: integer(64) }
    batch_start_year:       { type: integer(64) }
    acad_year_no:           { type: integer(64) }
    fees_type:               { type: integer(64) }
    course_type:            { type: integer(64) }
    amount:                  { type: integer(64) }

  relations:
    FeesCategory:           { class: FeesTypes, local: fees_type, foreign: id }
    CourseCategory:        { class: CourseTypes, local: course_type, foreign: id }


FeesTypes:
  actAs:           [Timestampable, SoftDelete]
  columns:
    name:                   { type: string(256) }